# Generated by Django 3.2 on 2021-12-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='weight',
        ),
        migrations.AddField(
            model_name='sales',
            name='customer',
            field=models.CharField(default='Anonymous', max_length=180),
        ),
    ]
