# Generated by Django 3.2 on 2021-12-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_auto_20211208_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('activity1', models.CharField(max_length=100)),
                ('activity2', models.CharField(blank=True, max_length=100)),
                ('activity3', models.CharField(blank=True, max_length=100)),
                ('activity4', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('activity', models.CharField(max_length=100)),
                ('investment', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='sales',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='sales',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='sales',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
